version: '3'

services:
    app: 
        environment: 
            SECRET_KEY: ${SECRET_KEY}
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
        build: ./app
        restart: always
        volumes:
            - ./app/MonitorServers:/codigo
        depends_on: 
            - bd
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: "512M"
    
    bd:
        image: mariadb:10.2.21
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes: 
            - ../data_mysql_proy2020:/var/lib/mysql
    
    nginx:
        image: nginx
        restart: always
        ports:
            - 9000:80
            - 8000:443 #se redirige al 80 de nginx
        volumes:
            - ./nginx/certs:/tmp
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - app
    tty:
        build: ./app_tty
        ports: 
            - 8888:8888